Development
TIHBS/blockchain-access-layer-api pull request #1
Opened 2022-02-01 19:04 UTC by akshay-ap

2022-02-02 10:19 UTC, ghareeb-falazi requested changes
Please consider the comments

2022-02-02 10:19 UTC, ghareeb-falazi commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/IAdapterExtenstion.java
> + * Copyright (c) 2019 Institute for the Architecture of Application System - University of Stuttgart
Please change the year to 2022

2022-02-02 10:19 UTC, ghareeb-falazi commented on pom.xml
> +        <dependency>
this is an Ethereum-specific library. Why do we need it in the API?

2022-02-02 10:19 UTC, ghareeb-falazi commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/contracts/Permissions.java
> +package blockchains.iaas.uni.stuttgart.de.api.contracts;
This file is used for testing. I think this one should be in the App rather than the api (It is code to communicate with a specific toy smart contract in Ethereum)

2022-02-02 10:19 UTC, ghareeb-falazi commented on pom.xml
> +        <dependency>
Could you make sure that all dependencies in this pom file are actually used? For example, intuitively I think that rpc.server is not needed by this repository, but I might be wrong

2022-02-02 10:19 UTC, ghareeb-falazi commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/AbstractAdapter.java
> +public abstract class AbstractAdapter implements BlockchainAdapter {
I don't this class is very useful in the API. I also think it is an overkill in general. Let's remove it from here, and add its code to the Ethereum and Bitcoin adapters (it is only useful there - PoW blockchains - )

2022-02-02 10:19 UTC, ghareeb-falazi commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/connectionprofiles/ConnectionProfileListener.java
> +public interface ConnectionProfileListener {
This interface is not useful in the API. It is only needed by the connection profile manager (in the app), so let's place it there.

2022-02-02 10:19 UTC, ghareeb-falazi commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/connectionprofiles/AbstractConnectionProfile.java
> +public abstract class AbstractConnectionProfile {
So, do you intend to place the blockchain-specific connection profiles within the blockchain-specific adapter repositories?

2022-02-04 20:04 UTC, akshay-ap commented on pom.xml
> +        <dependency>
This library is needed by the `Permissions` class. But, now as we are moving [Permissions.java](https://github.com/TIHBS/blockchain-access-layer-api/pull/1/files/e0ffa2b2a186096d2f13893ae80050081c4039c4#diff-5b8f2c559f92e24d23c2f55858ccd0463c3888b58d4e90cea51d597eb7489bde) to App/Plugin, we can remove this dependency.

2022-02-04 20:09 UTC, akshay-ap commented on src/main/java/blockchains/iaas/uni/stuttgart/de/api/connectionprofiles/AbstractConnectionProfile.java
> +public abstract class AbstractConnectionProfile {
Yes, that's the intention.

2022-02-04 20:13 UTC, akshay-ap commented on pom.xml
> +        <dependency>
Yes, all the added dependencies are used in the project. Although, I have added exclusions as they were in the main app repository.

2022-02-08 11:46 UTC, ghareeb-falazi approved these changes
Everything looks good to me at this stage.

2022-02-08 11:46 UTC, merged